### PR TITLE
Add backported subprocess.run to make sure it works in Python3.4

### PR DESCRIPTION
**Pull request by balta2ar**

### CODE REVIEW

**Comment by raghur** [comment]
Thanks for the PR.. Couple of questions (I've not used subprocess module outside of ghost :))

1. In `run`, why not check existence of run and just call run, else call the backported code?
2. https://docs.python.org/3/library/subprocess.html#call-function-trio provides simpler alternatives to run. Given that we never need to pass stdin or read the output, does it make sense to use the simpler versions?

**Comment by balta2ar** [comment]
That totally makes sense! My knee-jerk reaction was to provide a backport of `run`, but it's actually way simpler to just use `call`, please take a look.

**Comment by raghur** [comment]
👍 Thanks - that looks good. So we can just go to `subprocess.call`.. Can you squash the commit? I'll merge it after that.

**Comment by balta2ar** [comment]
Done.

**Pull request merged**
